# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4fe98dcac0cc405bf9e4460e5740a39b28ab94046245ca143b074cf71090abda3f22c79ff9a93a3fcb6ecc1c7c6635150f4f5ad3f564d526fd4f9c4fb132bc4

test:
  secret_key_base: 84b91e6f94a54d95558a24bfb1c47e49f35259de6c2355229284abe21a10ffa74324871aa53f45e039dc31948be2b58a95da445da88bac0d59bfbd07f474d161

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
